"""add_is_sold_to_items

Revision ID: 8d9fafb15f3a
Revises: b9d3de597693
Create Date: 2026-08-06 19:38:33.752116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9fafb15f3a'
down_revision: Union[str, Sequence[str], None] = 'b9d3de597693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_listing_snapshots_unique'), table_name='listing_snapshots')
    op.drop_table('listing_snapshots')
    op.add_column('items', sa.Column('is_sold', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_sold')
    op.create_table('listing_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorites', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('listing_snapshots_pkey'))
    )
    op.create_index(op.f('idx_listing_snapshots_unique'), 'listing_snapshots', ['listing_id', 'recorded_at'], unique=True)
    # ### end Alembic commands ###
